/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package programas;

import static java.awt.Frame.MAXIMIZED_BOTH;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Ezequiel
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() throws IOException {

        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);

        File F2 = new File("Us_actual.txt");
        try {
            if (!F2.exists()) {
                F2.createNewFile();
            }
            try (Scanner s = new Scanner(F2)) {
                if (s.hasNextLine()) {
                    String linea = s.nextLine();
                    Scanner sl = new Scanner(linea);
                    sl.useDelimiter("\\s*;\\s*");
                    sl.next();
                    sl.next();
                    String nivel_us = sl.next();

                    if ("1".equals(nivel_us)) {
                        menu_usuarios.setVisible(false);
                    }
                }
                s.close();
            } catch (Exception ex) {
                System.out.println("z01 " + ex);
            }
            F2.delete();
        } catch (FileNotFoundException e1) {
            System.out.println("x02 Error al leer Archivo " + e1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        modu_mantenimiento = new javax.swing.JMenu();
        menu_usuarios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuBar1.setPreferredSize(new java.awt.Dimension(297, 90));

        modu_mantenimiento.setIcon(new javax.swing.ImageIcon("C:\\lab_proyecto\\fotos\\mantenimiento.png")); // NOI18N
        modu_mantenimiento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modu_mantenimiento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        modu_mantenimiento.setPreferredSize(new java.awt.Dimension(100, 70));
        modu_mantenimiento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        modu_mantenimiento.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                modu_mantenimientoMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                modu_mantenimientoMouseMoved(evt);
            }
        });
        modu_mantenimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modu_mantenimientoMouseExited(evt);
            }
        });

        menu_usuarios.setIcon(new javax.swing.ImageIcon("C:\\lab_proyecto\\fotos\\usuario2.png")); // NOI18N
        menu_usuarios.setText("Usuarios");
        menu_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_usuariosActionPerformed(evt);
            }
        });
        modu_mantenimiento.add(menu_usuarios);

        jMenuBar1.add(modu_mantenimiento);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modu_mantenimientoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modu_mantenimientoMouseDragged

    }//GEN-LAST:event_modu_mantenimientoMouseDragged

    private void modu_mantenimientoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modu_mantenimientoMouseMoved
        modu_mantenimiento.doClick();
        modu_mantenimiento.setText("Mantenimientos");
    }//GEN-LAST:event_modu_mantenimientoMouseMoved

    private void modu_mantenimientoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modu_mantenimientoMouseExited
        modu_mantenimiento.setText("");
    }//GEN-LAST:event_modu_mantenimientoMouseExited

    private void menu_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_usuariosActionPerformed
        Usuarios abrir = new Usuarios();
        abrir.setVisible(true);
    }//GEN-LAST:event_menu_usuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         java.awt.EventQueue.invokeLater(() -> {
            try {
                new principal().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menu_usuarios;
    private javax.swing.JMenu modu_mantenimiento;
    // End of variables declaration//GEN-END:variables
}
