/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package programas;

import java.awt.Graphics;
import java.awt.Image;
import static programas.ManejoArchivo.Buscar;
import static programas.ManejoArchivo.Crear;
import static programas.ManejoArchivo.Modificar;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Angel Baez
 */
public class Usuarios extends javax.swing.JFrame {

    /**
     * Creates new form Usuarios
     */
    Boolean modi = false;
    String tabla = "Usuarios.txt";
    int campos = 6;
   

    public Usuarios() {
        
        initComponents();
        this.setSize(512, 574);
        this.setLocationRelativeTo(null);

        jLabel1.setText("<html><u>Usuario</u></html>");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jLabel6 = new javax.swing.JLabel();
        textfield1 = new javax.swing.JTextField();
        textfield3 = new javax.swing.JTextField();
        textfield4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        textfield5 = new javax.swing.JTextField();
        textfield6 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        titulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Usuarios");
        setMinimumSize(new java.awt.Dimension(10, 10));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Usuario:");
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel1MouseMoved(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 170, 45, 17);

        jLabel2.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel2.setText("Contraseña:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 220, 65, 17);

        jLabel3.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 270, 46, 17);

        jLabel4.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel4.setText("Apellido:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 310, 48, 17);

        jLabel5.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel5.setText("Correo:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 350, 50, 17);

        jSlider1.setMaximum(1);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        getContentPane().add(jSlider1);
        jSlider1.setBounds(270, 410, 56, 20);

        jLabel6.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel6.setText("Nivel de Acceso");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(170, 410, 81, 17);

        textfield1.setPreferredSize(new java.awt.Dimension(64, 28));
        textfield1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textfield1FocusLost(evt);
            }
        });
        textfield1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textfield1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textfield1KeyReleased(evt);
            }
        });
        getContentPane().add(textfield1);
        textfield1.setBounds(170, 170, 272, 28);

        textfield3.setPreferredSize(new java.awt.Dimension(64, 28));
        textfield3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textfield3KeyReleased(evt);
            }
        });
        getContentPane().add(textfield3);
        textfield3.setBounds(170, 260, 272, 30);

        textfield4.setPreferredSize(new java.awt.Dimension(64, 28));
        textfield4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textfield4KeyReleased(evt);
            }
        });
        getContentPane().add(textfield4);
        textfield4.setBounds(170, 310, 272, 28);

        jButton1.setText("guardar");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(140, 470, 110, 40);

        textfield5.setPreferredSize(new java.awt.Dimension(64, 28));
        getContentPane().add(textfield5);
        textfield5.setBounds(170, 350, 272, 28);

        textfield6.setEditable(false);
        textfield6.setText("1");
        textfield6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield6ActionPerformed(evt);
            }
        });
        getContentPane().add(textfield6);
        textfield6.setBounds(340, 410, 29, 22);

        jPasswordField1.setPreferredSize(new java.awt.Dimension(64, 28));
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyReleased(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(170, 220, 272, 28);

        titulo.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Crear Usuario");
        getContentPane().add(titulo);
        titulo.setBounds(140, 80, 340, 50);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(500, 10, 10, 10);
        getContentPane().add(jPanel2);
        jPanel2.setBounds(528, 10, 10, 10);

        jButton3.setText("eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(280, 490, 73, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textfield6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield6ActionPerformed

    }//GEN-LAST:event_textfield6ActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        textfield6.setText(Integer.toString(jSlider1.getValue()));
    }//GEN-LAST:event_jSlider1StateChanged

    private void textfield1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textfield1FocusLost
        String[] datos = new String[campos + 1];
        if ("".equals(textfield1.getText())) {
            textfield3.setText("");
            textfield4.setText("");
            textfield5.setText("");
            jPasswordField1.setText("");
            titulo.setText("Crear Usuario");
            modi = false;

        } else {
            try {
                datos = Buscar(textfield1.getText(), tabla, campos);
            } catch (IOException ex) {
                Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if ("1".equals(datos[6])) {
            textfield3.setText(datos[2]);
            textfield4.setText(datos[3]);
            textfield5.setText(datos[4]);
            jPasswordField1.setText(datos[1]);
            jSlider1.setValue(Integer.parseInt(datos[5]));
            titulo.setText("Modificar Usuario");
            modi = true;
        } else {
            textfield3.setText("");
            textfield4.setText("");
            textfield5.setText("");
            jPasswordField1.setText("");
            titulo.setText("Crear Usuario");
        }
    }//GEN-LAST:event_textfield1FocusLost

    private void textfield1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfield1KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jPasswordField1.requestFocus();
        }
    }//GEN-LAST:event_textfield1KeyReleased

    private void jPasswordField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            textfield3.requestFocus();
        }
    }//GEN-LAST:event_jPasswordField1KeyReleased

    private void textfield3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfield3KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            textfield4.requestFocus();
        }
    }//GEN-LAST:event_textfield3KeyReleased

    private void textfield4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfield4KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            textfield5.requestFocus();
        }
    }//GEN-LAST:event_textfield4KeyReleased

    private void textfield1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfield1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield1KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String[] crear = new String[campos];
        crear[0] = textfield1.getText();
        crear[1] = new String(jPasswordField1.getPassword());
        crear[2] = textfield3.getText();
        crear[3] = textfield4.getText();
        crear[4] = textfield5.getText();
        crear[5] = Integer.toString(jSlider1.getValue());

        if ("".equals(crear[0])) {
            JOptionPane.showMessageDialog(rootPane, "FALTAN CAMPOS POR DIGITAR");
        } else if ("".equals(crear[1])) {
            JOptionPane.showMessageDialog(rootPane, "FALTAN CAMPOS POR DIGITAR");
        } else if ("".equals(crear[2])) {
            JOptionPane.showMessageDialog(rootPane, "FALTAN CAMPOS POR DIGITAR");
        } else if ("".equals(crear[3])) {
            JOptionPane.showMessageDialog(rootPane, "FALTAN CAMPOS POR DIGITAR");
        } else if ("".equals(crear[4])) {
            JOptionPane.showMessageDialog(rootPane, "FALTAN CAMPOS POR DIGITAR");
        } else {
            if (modi == false) {
                try {
                    Crear(crear, tabla);
                    JOptionPane.showMessageDialog(rootPane, "DATOS GUARDADOS");
                    textfield1.setText("");
                    textfield3.setText("");
                    textfield4.setText("");
                    textfield5.setText("");
                    jPasswordField1.setText("");
                } catch (FileNotFoundException | UnsupportedEncodingException ex) {
                    Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                Modificar(crear, tabla);
                JOptionPane.showMessageDialog(rootPane, "DATOS GUARDADOS");
                textfield1.setText("");
                textfield3.setText("");
                textfield4.setText("");
                textfield5.setText("");
                jPasswordField1.setText("");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseMoved

    }//GEN-LAST:event_jLabel1MouseMoved

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        consulta_usuarios abrir = new consulta_usuarios();
        abrir.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged

    }//GEN-LAST:event_jLabel1MouseDragged

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited

    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered

    }//GEN-LAST:event_jLabel1MouseEntered
    public static boolean borrarUsuario(String archivo, String usuarioABorrar) {
        try {
            File inputFile = new File(archivo);
            File tempFile = new File("temp.txt");

            if (!inputFile.exists()) {
                System.out.println("El archivo '" + archivo + "' no existe.");
                return false;
            }

            BufferedReader reader = new BufferedReader(new FileReader(inputFile));
            BufferedWriter writer = new BufferedWriter(new FileWriter(tempFile));

            String lineaActual;
            boolean usuarioEncontrado = false;

            // Leer línea por línea del archivo original
            while ((lineaActual = reader.readLine()) != null) {
                String[] datosUsuario = lineaActual.trim().split(" ");

                // Si la línea contiene datos de usuario y el usuario coincide, no copiarla en el archivo temporal (borrarla)
                if (datosUsuario.length > 0 && datosUsuario[0].equals(usuarioABorrar)) {
                    usuarioEncontrado = true;
                    continue;
                }

                // Copiar la línea actual al archivo temporal
                writer.write(lineaActual);
                writer.newLine();
            }

            // Cerrar los lectores y escritores
            reader.close();
            writer.close();

            if (usuarioEncontrado) {
                // Eliminar el archivo original y renombrar el archivo temporal para tener el mismo nombre
                if (inputFile.delete()) {
                    tempFile.renameTo(inputFile);
                    System.out.println("El usuario '" + usuarioABorrar + "' ha sido borrado del archivo.");
                    return true;
                } else {
                    System.out.println("No se pudo borrar el usuario '" + usuarioABorrar + "' del archivo.");
                    return false;
                }
            } else {
                System.out.println("El usuario '" + usuarioABorrar + "' no fue encontrado en el archivo.");
                return false;
            }

        } catch (IOException e) {
            e.printStackTrace();
            return false;
        }
    }


    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String archivoTxt = "Usuarios.txt";
        String usuarioABorrar = textfield1.getText();
        borrarUsuario(archivoTxt, usuarioABorrar);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField textfield1;
    private javax.swing.JTextField textfield3;
    private javax.swing.JTextField textfield4;
    private javax.swing.JTextField textfield5;
    private javax.swing.JTextField textfield6;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables

}
